### PR TITLE
Use master jenkins shared pipeline

### PR DESCRIPTION
**Pull request by ameenhaq**
Updated the public library to master

### CODE REVIEW

**Review by willis7 — CHANGES_REQUESTED** [review]
"Updated Jenkinsfile" isn't useful as a commit message - git tells me that already "Use master jenkins shared pipeline" is way more informative.

**Comment by willis7** [comment]
Reworded commit message and rebased from develop. Ready for merge.

**Review by willis7 — DISMISSED** [review]

**Comment by willis7** [comment]
Looks like I got a rotten deal picking this up. The build pipeline doesn't build and the problem isn't this update as it's proven in other services. 

It appears there are bugs in the Jenkinsfile that I'm working through at the moment.

**Comment by willis7** [comment]
It looks like the logic to only build when there's a match on branch name is broken. I'm not sure if this has ever worked, but I was able to replicate the behavior using `when{ expression{ isBranch(BRANCH_DEV)}}`. I created the `isBranch(branchName)` helper in the file, but this should make its way to the shared pipeline.

all the fixups have been squashed and this is now ready for review. @ameenhaq, @awharris

**Review by ameenhaq — COMMENTED** [review]
The failure is due to an update to the 'GitHub Integration' plugin - we our using the temporary solution similar to yours already. Clearly a more serious underlying problem exist with allowing plugins being updated that disrupts build files - @willis7 as I've raised with you or maybe something @awharris can look into

**Review by willis7 — APPROVED** [review]

**Pull request merged**
